package br.net.unicom.backend.model;

public enum RegistroJornadaCorrecaoObservacaoEnum {
    HORAS_DEVIDAS_PAGAS, ATESTADO_MEDICO, FALTA_NAO_JUSTIFICADA, FALTA_JUSTIFICADA, FOLGA_CONCEDIDA, HOME_OFFICE, SUSPENSO, DESLIGAMENTO, PRESENTE;
}
